Add views
BranBayou/ror-blog-app pull request #6
Opened 2023-11-02 20:16 UTC by BranBayou

### In this project I did the following.

- Implemented view design based on the sneak peek wireframes.

-    view for user
-    view for post

- Analyzed the wireframes deeply and identified all the necessary elements and how a user would navigate from one page to another.

2023-11-02 21:42 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @BranBayou 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-02 21:42 UTC, codepantha commented on app/views/users/index.html.erb
> +</ul>
- [ ] Please ensure that the index page implements the design from the wireframe. You don't have to style it but kindly ensure that the wireframe design is implemented 👍 
### Wireframe design
![image](https://github.com/BranBayou/ror-blog-app/assets/46839548/f76c07e5-f786-4fa8-b36d-5ee6fd8d3099)

### Your implementation
![image](https://github.com/BranBayou/ror-blog-app/assets/46839548/eb3f98b5-244e-4733-ba00-8a49e05250fe)

2023-11-02 21:42 UTC, codepantha commented on app/views/users/show.html.erb
> +<div class='see-all-post-btn-container'><%= link_to "See all posts", user_posts_path(@user), class: 'see-all-post-btn' %></div>
- [ ] Also kindly ensure that the user show page follows and closely implements the wireframe guidelines as shown below 👇 
### Wireframe
![image](https://github.com/BranBayou/ror-blog-app/assets/46839548/30cf5aca-94c2-49c0-8e48-78052d6413ee)

### Your Implementation
![image](https://github.com/BranBayou/ror-blog-app/assets/46839548/cf89c241-3b03-489a-9807-34aee5a58ce9)

2023-11-02 21:42 UTC, codepantha commented on app/views/posts/index.html.erb
> +<div class='see-all-post-btn-container'><a class='see-all-post-btn'>Pagination</a></div>
- [ ] An error occurs while trying to show all posts that belong to a user. Kindly see the error below and try to fix it 👇 
![image](https://github.com/BranBayou/ror-blog-app/assets/46839548/0f945bf7-c0ac-401a-91b2-bf3343ba9ed4)

2023-11-03 11:26 UTC, cynthiainga approved these changes
Hi @BranBayou, 

## STATUS APPROVED ✔️ 🎉 🎉 ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] Requested changes are made ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-03 11:58 UTC, merged